# -*- coding: utf-8 -*-
"""pgswin_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1g9YsyyePcxxuKYFeZBljvDbuTJFE1X

# PG-Swin: Prototype-Guided Shifted-Swin bottleneck (continuation of `run_swin_bottleneck.py`)
Run the cells **in order**, in the same Colab session where `multiseed_pipeline.py`, `repro_utils.py`, `shared_losses.py`,
`models_phase1.py`, `models_phase1_swin.py` are already in the working directory. Nothing existing is modified; all results go to `phase1_pgswin/`.

**Three changes over the current Swin bottleneck**
1. *Real* Swin: alternating W-MSA / **shifted** SW-MSA with attention mask, LayerScale (init 0.1) instead of `alpha=0` (which gives the Swin branch zero gradient at start).
2. **Image-conditioned class prototypes**: learnable tokens (2 per class) cross-attend to the bottleneck (global context) and are matched by cosine similarity to full-resolution decoder features, so global anatomy reaches the 1x1x1 voxel logits directly.
3. **Deep supervision + weight EMA** (training-only, free at inference). A control arm with ds+EMA but no Swin/prototypes is included so the architecture gain is not confounded.

## Cell 1: model file
"""

import sys, os
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

ARRAY_DIR = "/content/drive/MyDrive/Array"
if ARRAY_DIR not in sys.path:
    sys.path.insert(0, ARRAY_DIR)

print("Array in sys.path:", ARRAY_DIR in sys.path)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models_pgswin.py
# # -*- coding: utf-8 -*-
# import math
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# from models_phase1 import HybridResUNet3DBase
# from models_phase1_swin import WindowAttention3D
# 
# 
# def _wpart(x, ws):
#     """(B,D,H,W,C) -> (B*nW, N, C); windows ordered (nD,nH,nW) inside each batch item."""
#     B, D, H, W, C = x.shape
#     wd, wh, ww = ws
#     x = x.reshape(B, D // wd, wd, H // wh, wh, W // ww, ww, C)
#     return x.permute(0, 1, 3, 5, 2, 4, 6, 7).reshape(-1, wd * wh * ww, C)
# 
# 
# def _wrev(w, ws, B, D, H, W):
#     wd, wh, ww = ws
#     C = w.shape[-1]
#     x = w.reshape(B, D // wd, H // wh, W // ww, wd, wh, ww, C)
#     return x.permute(0, 1, 4, 2, 5, 3, 6, 7).reshape(B, D, H, W, C)
# 
# 
# def _shift_mask(Dp, Hp, Wp, ws, ss, device):
#     """Standard Swin SW-MSA mask in 3D: tokens that were wrapped around by the
#     cyclic shift must not attend to tokens from a different region."""
#     img = torch.zeros(1, Dp, Hp, Wp, 1, device=device)
# 
#     def sl(w, s):
#         return (slice(0, -w), slice(-w, -s), slice(-s, None)) if s > 0 else (slice(None),)
# 
#     cnt = 0
#     for d in sl(ws[0], ss[0]):
#         for h in sl(ws[1], ss[1]):
#             for w_ in sl(ws[2], ss[2]):
#                 img[:, d, h, w_, :] = cnt
#                 cnt += 1
#     mw = _wpart(img, ws).squeeze(-1)                       # (nW, N)
#     m = mw.unsqueeze(1) - mw.unsqueeze(2)                  # (nW, N, N)
#     return m.masked_fill(m != 0, -100.0).masked_fill(m == 0, 0.0)
# 
# 
# class MaskedWindowAttention3D(WindowAttention3D):
#     """Re-uses the relative-position-bias attention of models_phase1_swin, adds the shift mask."""
#     def forward(self, x, mask=None):
#         B_, N, C = x.shape
#         qkv = self.qkv(x).reshape(B_, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
#         q, k, v = qkv[0], qkv[1], qkv[2]
#         attn = (q * self.scale) @ k.transpose(-2, -1)
#         bias = self.relative_position_bias_table[self.relative_position_index.view(-1)]
#         attn = attn + bias.view(N, N, -1).permute(2, 0, 1).contiguous().unsqueeze(0)
#         if mask is not None:
#             nW = mask.shape[0]
#             attn = attn.view(B_ // nW, nW, self.num_heads, N, N) + mask.unsqueeze(1).unsqueeze(0)
#             attn = attn.view(-1, self.num_heads, N, N)
#         attn = self.attn_drop(self.softmax(attn))
#         x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
#         return self.proj_drop(self.proj(x))
# 
# 
# class SwinBlock3D(nn.Module):
#     """Pre-norm Swin block, channel-last, LayerScale residuals. shift=True -> SW-MSA."""
#     def __init__(self, dim, heads, ws, shift, mlp_ratio=2.0, drop=0.1, ls_init=0.1):
#         super().__init__()
#         self.ws, self.shift = ws, shift
#         self.norm1 = nn.LayerNorm(dim)
#         self.attn = MaskedWindowAttention3D(dim, ws, heads, qkv_bias=True, attn_drop=0.0, proj_drop=drop)
#         self.norm2 = nn.LayerNorm(dim)
#         hid = int(dim * mlp_ratio)
#         self.mlp = nn.Sequential(nn.Linear(dim, hid), nn.GELU(), nn.Dropout(drop),
#                                  nn.Linear(hid, dim), nn.Dropout(drop))
#         self.g1 = nn.Parameter(ls_init * torch.ones(dim))
#         self.g2 = nn.Parameter(ls_init * torch.ones(dim))
#         self._mask_cache = {}
# 
#     def _mask(self, Dp, Hp, Wp, ss, device):
#         key = (Dp, Hp, Wp, ss, str(device))
#         if key not in self._mask_cache:
#             self._mask_cache[key] = _shift_mask(Dp, Hp, Wp, self.ws, ss, device)
#         return self._mask_cache[key]
# 
#     def forward(self, x):                                   # x: (B,D,H,W,C)
#         B, D, H, W, C = x.shape
#         wd, wh, ww = self.ws
#         pd_, ph, pw = (-D) % wd, (-H) % wh, (-W) % ww
#         h = self.norm1(x)
#         if pd_ or ph or pw:
#             h = F.pad(h, (0, 0, 0, pw, 0, ph, 0, pd_))
#         Dp, Hp, Wp = D + pd_, H + ph, W + pw
#         ss = (wd // 2 if Dp > wd else 0, wh // 2 if Hp > wh else 0, ww // 2 if Wp > ww else 0) \
#             if self.shift else (0, 0, 0)
#         mask = None
#         if any(ss):
#             h = torch.roll(h, shifts=(-ss[0], -ss[1], -ss[2]), dims=(1, 2, 3))
#             mask = self._mask(Dp, Hp, Wp, ss, x.device)
#         h = self.attn(_wpart(h, self.ws), mask)
#         h = _wrev(h, self.ws, B, Dp, Hp, Wp)
#         if any(ss):
#             h = torch.roll(h, shifts=ss, dims=(1, 2, 3))
#         h = h[:, :D, :H, :W, :]
#         x = x + self.g1 * h
#         return x + self.g2 * self.mlp(self.norm2(x))
# 
# 
# class SwinStage3D(nn.Module):
#     """depth blocks alternating W-MSA / SW-MSA. In/out: (B,C,D,H,W)."""
#     def __init__(self, dim, heads=4, ws=(2, 4, 4), depth=2, drop=0.1):
#         super().__init__()
#         self.blocks = nn.ModuleList([SwinBlock3D(dim, heads, ws, shift=(i % 2 == 1), drop=drop)
#                                      for i in range(depth)])
# 
#     def forward(self, x):
#         x = x.permute(0, 2, 3, 4, 1).contiguous()
#         for blk in self.blocks:
#             x = blk(x)
#         return x.permute(0, 4, 1, 2, 3).contiguous()
# 
# 
# class PrototypeHead3D(nn.Module):
#     """Image-conditioned class prototypes.
#     Learnable tokens (K classes x P prototypes) cross-attend to ALL bottleneck tokens (global
#     context, bottleneck is tiny), are projected to the decoder width and compared (cosine) to
#     full-resolution decoder features. Returns an additive logit map (B,K,D,H,W)."""
#     def __init__(self, c_bott, c_feat, num_classes=2, protos_per_class=2, heads=4,
#                  drop=0.1, tau_init=10.0, gamma_init=0.1):
#         super().__init__()
#         self.K, self.P = num_classes, protos_per_class
#         self.proto = nn.Parameter(torch.randn(self.K * self.P, c_bott) * 0.02)
#         self.norm_q = nn.LayerNorm(c_bott)
#         self.norm_kv = nn.LayerNorm(c_bott)
#         self.xattn = nn.MultiheadAttention(c_bott, heads, dropout=drop, batch_first=True)
#         self.norm_f = nn.LayerNorm(c_bott)
#         self.ffn = nn.Sequential(nn.Linear(c_bott, 2 * c_bott), nn.GELU(), nn.Linear(2 * c_bott, c_bott))
#         self.to_feat = nn.Linear(c_bott, c_feat)
#         self.pix_proj = nn.Conv3d(c_feat, c_feat, 1)
#         self.log_tau = nn.Parameter(torch.tensor(math.log(tau_init)))
#         self.gamma = nn.Parameter(torch.tensor(float(gamma_init)))   # non-zero: gradients flow from step 1
# 
#     def forward(self, bott, d1):
#         B = bott.shape[0]
#         tok = self.norm_kv(bott.flatten(2).transpose(1, 2))          # (B,N,C)
#         q = self.proto.unsqueeze(0).expand(B, -1, -1)
#         a, _ = self.xattn(self.norm_q(q), tok, tok, need_weights=False)
#         p = q + a
#         p = p + self.ffn(self.norm_f(p))
#         p = F.normalize(self.to_feat(p), dim=-1)                      # (B,KP,f)
#         f = F.normalize(self.pix_proj(d1), dim=1)                     # (B,f,D,H,W)
#         sim = torch.einsum("bfdhw,bpf->bpdhw", f, p)
#         sim = sim.reshape(B, self.K, self.P, *sim.shape[2:]).amax(2)  # best prototype per class
#         return self.gamma * self.log_tau.exp() * sim
# 
# 
# class PGSwinUNet3D(HybridResUNet3DBase):
#     """Phase-1 ResUNet3D + (optional) shifted-Swin bottleneck + (optional) prototype head
#     + (optional) deep supervision. All flags False -> plain Phase-1 baseline."""
#     def __init__(self, cfg, use_swin=True, use_proto=True, deep_sup=True,
#                  swin_window=(2, 4, 4), swin_heads=4, swin_depth=2, protos_per_class=2):
#         super().__init__(cfg)
#         f, out_ch = cfg["init_features"], cfg["num_classes"]
#         self.use_swin, self.use_proto, self.deep_sup = use_swin, use_proto, deep_sup
#         if use_swin:
#             self.swin = SwinStage3D(f * 8, swin_heads, swin_window, swin_depth, drop=0.1)
#         if use_proto:
#             self.proto = PrototypeHead3D(f * 8, f, out_ch, protos_per_class)
#         self.final_conv = nn.Conv3d(f, out_ch, 1)
#         if deep_sup:
#             self.aux3 = nn.Conv3d(f * 4, out_ch, 1)
#             self.aux2 = nn.Conv3d(f * 2, out_ch, 1)
#         self._init_weights()      # only touches Conv3d / GroupNorm, as in the baseline
# 
#     def forward(self, x):
#         s1, s2, s3, b = self.encode(x)
#         if self.use_swin:
#             b = self.swin(b)
#         d3 = self.dec3(torch.cat([s3, self.up3(b)], 1))
#         d2 = self.dec2(torch.cat([s2, self.up2(d3)], 1))
#         d1 = self.dec1(torch.cat([s1, self.up1(d2)], 1))
#         logits = self.final_conv(d1)
#         if self.use_proto:
#             logits = logits + self.proto(b, d1)
#         if self.training and self.deep_sup:
#             sz = logits.shape[2:]
#             aux = [F.interpolate(self.aux2(d2), size=sz, mode="trilinear", align_corners=False),
#                    F.interpolate(self.aux3(d3), size=sz, mode="trilinear", align_corners=False)]
#             return logits, aux
#         return logits            # eval: plain tensor -> works with evaluate_per_subject unchanged

"""## Cell 2: smoke test (run this before any training)"""

import importlib, torch, models_pgswin
importlib.reload(models_pgswin)
from models_pgswin import PGSwinUNet3D
dev = "cuda" if torch.cuda.is_available() else "cpu"
cfg_t = dict(init_features=16, norm_groups=8, dropout_rate=0.2, in_channels=1, num_classes=2)

for shape in [(2, 1, 32, 48, 32), (1, 1, 24, 40, 24)]:       # second one forces padding in the Swin windows
    m = PGSwinUNet3D(cfg_t).to(dev).train()
    x = torch.randn(*shape, device=dev)
    logits, aux = m(x)
    assert logits.shape == (shape[0], 2, *shape[2:]) and all(a.shape == logits.shape for a in aux)
    (logits.mean() + sum(a.mean() for a in aux)).backward()
    g_swin = m.swin.blocks[0].attn.qkv.weight.grad.abs().sum().item()
    g_proto = m.proto.proto.grad.abs().sum().item()
    print(shape, "OK | params %.2fM | grad swin %.3g | grad proto %.3g" %
          (sum(p.numel() for p in m.parameters()) / 1e6, g_swin, g_proto))
    assert g_swin > 0 and g_proto > 0
    m.eval()
    with torch.no_grad():
        assert m(x).shape == (shape[0], 2, *shape[2:])
print("smoke test passed")

"""## Cell 3: training utilities (EMA + deep supervision), new result folder"""

import os, glob, json, time, copy
import numpy as np, pandas as pd, torch, torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
from multiseed_pipeline import (DEVICE, CLASS_NAMES, set_seed, load_from_manifest_npz_with_ids,
    audit_empty_masks, make_loaders, evaluate_per_subject, seed_level_table,
    paired_seed_level_test, hierarchical_bootstrap, adjust_pvalues,
    MANIFEST_PATH, NPZ_CACHE_ROOT, RESULTS_ROOT)
from repro_utils import build_run_fingerprint, fingerprint_matches, save_fingerprint, validate_percase_csv
from shared_losses import BCEDiceLoss
from models_pgswin import PGSwinUNet3D

PG_ROOT = os.path.join(RESULTS_ROOT, "phase1_pgswin")
for sub in ("tables", "checkpoints"):
    os.makedirs(os.path.join(PG_ROOT, sub), exist_ok=True)

# control arm (ctrl_ds_ema) has NO swin / prototypes: it isolates the effect of the training tricks
VARIANTS = {
   # "ctrl_ds_ema":   dict(use_swin=False, use_proto=False, deep_sup=True,  ema=True),
   # "sw_swin":       dict(use_swin=True,  use_proto=False, deep_sup=False, ema=False),
   # "sw_swin_proto": dict(use_swin=True,  use_proto=True,  deep_sup=False, ema=False),
    "pgswin_full":   dict(use_swin=True,  use_proto=True,  deep_sup=True,  ema=True),
}
DS_WEIGHTS = (0.5, 0.25)          # nnU-Net style halving, main output has weight 1
EMA_DECAY = 0.995


def build_pg(cfg, v):
    return PGSwinUNet3D(cfg, use_swin=v["use_swin"], use_proto=v["use_proto"], deep_sup=v["deep_sup"])


@torch.no_grad()
def ema_update(ema, model, step, decay=EMA_DECAY):
    d = min(decay, (1 + step) / (10 + step))
    for pe, p in zip(ema.parameters(), model.parameters()):
        pe.mul_(d).add_(p.detach(), alpha=1 - d)
    for be, b in zip(ema.buffers(), model.buffers()):
        be.copy_(b)


@torch.no_grad()
def val_dice_of(m, loader):
    m.eval(); out = []
    for imgs, masks, _, _, _ in loader:
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        preds = (torch.sigmoid(m(imgs)) > 0.5).float()
        inter = (preds * masks).sum(dim=(2, 3, 4))
        card = (preds + masks).sum(dim=(2, 3, 4)) + 1e-5
        out.append(((2.0 * inter + 1e-5) / card).mean().item())
    return float(np.mean(out))


def train_one_v2(model, loaders, epochs, loss_fn, run_dir, cfg, v, tag=""):
    os.makedirs(run_dir, exist_ok=True)
    last_path, best_path = os.path.join(run_dir, "last.pt"), os.path.join(run_dir, "best.pt")
    model = model.to(DEVICE)
    ema = copy.deepcopy(model).eval() if v["ema"] else None
    eval_model = ema if v["ema"] else model            # the model that is validated / saved / tested
    opt = optim.AdamW(model.parameters(), lr=cfg["lr"], weight_decay=cfg["weight_decay"])
    sched = CosineAnnealingLR(opt, T_max=epochs)
    start_epoch, best_val, best_epoch, step = 1, -1.0, 0, 0
    history = {"train_loss": [], "val_dice": [], "epoch_time_sec": []}

    if os.path.exists(last_path):
        ck = torch.load(last_path, map_location=DEVICE, weights_only=False)
        model.load_state_dict(ck["model_state"]); opt.load_state_dict(ck["optimizer_state"])
        sched.load_state_dict(ck["scheduler_state"])
        if ema is not None: ema.load_state_dict(ck["ema_state"])
        start_epoch, best_val, best_epoch = ck["epoch"] + 1, ck["best_val_dice"], ck["best_epoch"]
        history, step = ck["history"], ck["step"]
        print(f"[{tag}] resuming from epoch {start_epoch}/{epochs}")

    if start_epoch > epochs:
        eval_model.load_state_dict(torch.load(best_path, map_location=DEVICE, weights_only=False))
        return eval_model, history

    for epoch in range(start_epoch, epochs + 1):
        t0 = time.time(); model.train(); running = 0.0
        for imgs, masks, edts, _, _ in loaders["train"]:
            imgs, masks, edts = imgs.to(DEVICE), masks.to(DEVICE), edts.to(DEVICE)
            out = model(imgs)
            if isinstance(out, tuple):                 # deep supervision
                logits, aux = out
                loss = loss_fn(logits, masks, edts)
                for w, a in zip(DS_WEIGHTS, aux):
                    loss = loss + w * loss_fn(a, masks, edts)
                loss = loss / (1.0 + sum(DS_WEIGHTS))
            else:
                loss = loss_fn(out, masks, edts)
            opt.zero_grad(); loss.backward(); opt.step()
            if ema is not None:
                ema_update(ema, model, step)
            step += 1; running += loss.item()
        sched.step()
        history["train_loss"].append(running / len(loaders["train"]))
        vd = val_dice_of(eval_model, loaders["val"])
        history["val_dice"].append(vd); history["epoch_time_sec"].append(time.time() - t0)
        print(f"[{tag}] epoch {epoch:03d}/{epochs} | loss {history['train_loss'][-1]:.4f} | "
              f"val_dice {vd:.4f} | {history['epoch_time_sec'][-1]:.1f}s")
        if vd > best_val:
            best_val, best_epoch = vd, epoch
            torch.save(eval_model.state_dict(), best_path)
        torch.save({"model_state": model.state_dict(), "optimizer_state": opt.state_dict(),
                    "scheduler_state": sched.state_dict(),
                    "ema_state": ema.state_dict() if ema is not None else None,
                    "epoch": epoch, "best_val_dice": best_val, "best_epoch": best_epoch,
                    "history": history, "step": step}, last_path)

    eval_model.load_state_dict(torch.load(best_path, map_location=DEVICE, weights_only=False))
    print(f"[{tag}] done -- best epoch {best_epoch}, val_dice {best_val:.4f}")
    return eval_model, history

"""## Cell 4: run the variants
Recommended order to save compute: first `SEEDS = [42, 43, 44]` and `ONLY = ["ctrl_ds_ema", "pgswin_full"]` as a **screen** (compare val Dice in the logs, no testing on test-set statistics),
then the full 10 seeds on the survivors. With only 5 seeds an exact Wilcoxon cannot go below p = 0.0625, so 10 seeds are required for a significance claim.
Runs are cached with the same fingerprint scheme as before, so you can re-run the cell after a Colab disconnect.
"""

CFG = dict(manifest_path=MANIFEST_PATH, npz_root=NPZ_CACHE_ROOT, num_classes=2, in_channels=1,
           init_features=16, batch_size=2, epochs=50, lr=5e-4, weight_decay=1e-4, dropout_rate=0.2,
           fusion="replace", norm_groups=8, refine_norm_groups=4, ms_kernel_size=3,
           use_max_pool_attention=False, gabor_kernel_size=5)

SEEDS = [42, 43, 44, 45, 46, 47, 48, 49, 50, 51]      # use [42, 43, 44] for the screen
ONLY = list(VARIANTS)                                  # e.g. ["ctrl_ds_ema", "pgswin_full"] for the screen

data = load_from_manifest_npz_with_ids(CFG["manifest_path"], CFG["npz_root"])
audit_empty_masks(data)
loaders = make_loaders(data, CFG["batch_size"], eval_batch_size=1)
expected_test_ids = list(data["test"][2])

for name in ONLY:
    v = VARIANTS[name]
    for seed in SEEDS:
        tag = f"{name}_seed{seed}"
        percase = os.path.join(PG_ROOT, "tables", f"per_case_{tag}.csv")
        run_dir = os.path.join(PG_ROOT, "checkpoints", tag)
        fp = build_run_fingerprint(dict(CFG, variant=name, **{f"v_{k}": val for k, val in v.items()}),
                                   CFG["manifest_path"], code_version="pgswin_v1",
                                   extra={"variant": name, "seed": seed, "ds_w": DS_WEIGHTS, "ema": EMA_DECAY})
        if os.path.exists(percase):
            fp_ok, _ = fingerprint_matches(run_dir, fp)
            csv_ok, _ = validate_percase_csv(percase, expected_test_ids, CLASS_NAMES)
            if fp_ok and csv_ok:
                print(f"[{tag}] cached -- skipping"); continue
            print(f"[{tag}] cache invalid -- will retrain")
        print(f"\n{'=' * 70}\n{tag}\n{'=' * 70}")
        set_seed(seed)
        model = build_pg(CFG, v)
        model, history = train_one_v2(model, loaders, CFG["epochs"], BCEDiceLoss(), run_dir, CFG, v, tag=tag)
        df = evaluate_per_subject(model, loaders["test"], DEVICE)
        df["optim_method"], df["seed"] = name, seed
        df.rename(columns={"klass": "klass_name"}, inplace=True)
        df.to_csv(percase, index=False)
        with open(os.path.join(PG_ROOT, "tables", f"history_{tag}.json"), "w") as fh:
            json.dump(history, fh)
        save_fingerprint(run_dir, fp)
        del model; torch.cuda.empty_cache()

1+1

"""## Cell 5: statistics vs baseline, Swin v1 and the ds+EMA control"""

def _load(pattern, label=None):
    files = sorted(glob.glob(pattern))
    assert files, f"nothing found for {pattern}"
    d = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
    if label: d["optim_method"] = label
    return d

pg   = _load(os.path.join(PG_ROOT, "tables", "per_case_*.csv"))
base = _load(os.path.join(RESULTS_ROOT, "phase1_architecture_ablation", "tables", "per_case_baseline_seed*.csv"), "baseline")
sw1  = _load(os.path.join(RESULTS_ROOT, "phase1_swin_bottleneck", "tables", "per_case_*.csv"), "swin_bottleneck")
alld = pd.concat([pg, base, sw1], ignore_index=True)
slevel = seed_level_table(alld)

# the first row is the PRIMARY claim; the others are explanatory (what produced the gain)
COMPARISONS = [("pgswin_full", "baseline"), ("pgswin_full", "swin_bottleneck"), ("pgswin_full", "ctrl_ds_ema"),
               ("ctrl_ds_ema", "baseline"), ("sw_swin", "swin_bottleneck"), ("sw_swin_proto", "sw_swin")]
present = set(alld.optim_method.unique())
rows = []
for a, b in COMPARISONS:
    if a not in present or b not in present: continue
    for kl in CLASS_NAMES:
        r = paired_seed_level_test(slevel, a, b, kl)
        bt = hierarchical_bootstrap(alld, a, b, kl)
        rows.append(dict(klass=kl, comparison=f"{a} vs {b}", **r, **bt))
stats = pd.DataFrame(rows)
stats["p_holm"], stats["p_bh_fdr"] = adjust_pvalues(stats["p_raw"].tolist())
stats["sig_holm"] = np.where(stats["p_holm"] < 0.05, "YES", "NO")

main = []
for kl in CLASS_NAMES:
    for m in ["baseline", "swin_bottleneck"] + [k for k in VARIANTS if k in present]:
        s = slevel[(slevel.optim_method == m) & (slevel.klass_name == kl)]
        if len(s): main.append(dict(klass=kl, method=m, n=s.seed.nunique(),
                                    dice=f"{s.seed_mean_dice.mean():.4f} +- {s.seed_mean_dice.std(ddof=1):.4f}",
                                    hd95=f"{s.seed_mean_hd95.mean():.3f}", assd=f"{s.seed_mean_assd.mean():.4f}"))
main = pd.DataFrame(main)
print(main.to_string(index=False))
print()
print(stats[["klass", "comparison", "mean_delta", "ci95_low", "ci95_high", "cohens_d", "p_raw", "p_holm", "sig_holm"]]
      .to_string(index=False))
main.to_csv(os.path.join(PG_ROOT, "tables", "pgswin_results.csv"), index=False)
stats.to_csv(os.path.join(PG_ROOT, "tables", "pgswin_pairwise.csv"), index=False)